Enabled Nvidia early KMS and tidied scripts

diff --git a/scripts/spotify-remove-banner b/scripts/spotify-remove-banner
--- a/scripts/spotify-remove-banner
+++ b/scripts/spotify-remove-banner
@@ -7,9 +7,9 @@ if [ "$1" == 'restore' ]; then
     if [ -w xpui.spa_bak ] && [ -w . ]; then
         rm -f xpui.spa
         mv xpui.spa_bak xpui.spa
-        echo "Restore success"
+        echo 'Restore success'
     else
-        [ -f xpui.spa_bak ] && echo "Permission denied" || echo "Backup not found"
+        [ -f xpui.spa_bak ] && echo 'Permission denied' || echo 'Backup not found'
     fi
     exit 0
 fi
@@ -19,7 +19,7 @@ if [ -w xpui.spa ] && [ -w . ]; then
     unzip -p xpui.spa xpui.js | sed 's/adsEnabled:\!0/adsEnabled:false/' > xpui.js
     zip --update xpui.spa xpui.js
     rm xpui.js
-    echo "Success"
+    echo 'Success'
 else
-    [ -f xpui.spa ] && echo "Permission denied" || echo "File not found"
+    [ -f xpui.spa ] && echo 'Permission denied' || echo 'File not found'
 fi
